import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";
import { afterEach, describe, expect, it, vi } from "vitest";
import { buildHybridVisualPlan } from "@/lib/hybrid-visuals";
import { makeDurationPlan } from "@/lib/editorial-duration";
import { applyTimingPlan, compileNaturalEditorialTiming } from "@/lib/editorial-timing";
import { ProductionCreateRequest, VideoCreateRequest } from "@/lib/schemas";
import { compileEditorialTimeline, renderEditorialAssets, timelineToAss } from "@/lib/server/news-delivery";
import { getStore, resetInMemoryStoreForDev } from "@/lib/server/store";
import { sourceCardSvg, readableEditorialMessage } from "@/lib/server/editorial-graphics";
import { outlineEditorialText } from "@/lib/server/render-fonts";
import { probeMediaFile } from "@/lib/server/media-probe";
import { buildSourceFirstDraft } from "@/workflow/source-first";
import { validateTimeline } from "@/lib/production";

// Opt in locally with a saved comparison MP4. No credentials or provider calls.
const directory = process.env.COCOA_RENDER_FIXTURES_DIR;
const baseline = process.env.COCOA_BASELINE_VIDEO;
afterEach(() => vi.unstubAllEnvs());
describe.skipIf(!directory || !baseline)("natural editorial render fixtures", () => {
  it.each(["16:9", "9:16"] as const)("renders complete captions and closing audio in %s", async (aspectRatio) => {
    vi.stubEnv("PROVIDER_MODE", "mock"); vi.stubEnv("DATABASE_URL", ""); vi.stubEnv("EDITORIAL_RENDER_MODE", "local");
    resetInMemoryStoreForDev();
    await mkdir(directory!, { recursive: true });
    const voice = join(directory!, "closing.wav");
    const score = join(directory!, "score.wav");
    execFileSync("ffmpeg", ["-v", "error", "-y", "-ss", "52.393", "-i", baseline!, "-t", "6.807", "-vn", "-ar", "48000", voice]);
    execFileSync("ffmpeg", ["-v", "error", "-y", "-f", "lavfi", "-i", "sine=frequency=220:duration=4:sample_rate=48000", score]);
    const narration = "OCPI is an hourly GPU-specific settlement reference for hedging and exposure, with stated safeguards and limits.";
    const request = ProductionCreateRequest.parse({ contentType: "explainer", brief: "Explain this sourced reference.", durationMode: "auto", qualityTier: "draft", aspectRatio, sourceBundle: { inputs: [{ id: "source", kind: "text", title: "Methodology", text: narration }], claims: [] } });
    const stored = await getStore().createJob(VideoCreateRequest.parse({ prompt: request.brief, durationSeconds: 60 }), { id: "render-fixture", email: "render@example.test", planTier: "dev", dailyBudgetCents: 1000 });
    const draft = buildSourceFirstDraft(stored.id, request);
    draft.storyboard.scenes[0].title = "An hourly reference with stated limits";
    const timing = compileNaturalEditorialTiming({ productionId: stored.id, storyboard: draft.storyboard, narration: [{ sceneId: draft.storyboard.scenes[0].id, durationMs: 6807 }], compiledAt: new Date().toISOString() });
    const original = buildHybridVisualPlan({ productionId: stored.id, request: { ...request, targetDurationSeconds: timing.targetDurationMs / 1000 }, storyboard: draft.storyboard, createdAt: timing.compiledAt });
    const timed = applyTimingPlan(draft.storyboard, original!, timing);
    const durationPlan = makeDurationPlan({ request, sourceBundle: draft.sourceBundle, scenes: timed.storyboard.scenes, now: timing.compiledAt });
    const job = { ...stored, contentType: request.contentType, aspectRatio, qualityTier: request.qualityTier, durationSeconds: timing.targetDurationMs / 1000, durationPlan, storyboard: timed.storyboard, visualPlan: timed.plan, sourceBundle: draft.sourceBundle };
    const words = narration.split(/\s+/).map((text, index, list) => ({ text, startMs: Math.round(index * 6807 / list.length), endMs: Math.round((index + 1) * 6807 / list.length) }));
    const audio = await readFile(voice);
    const assets = [{ narration: { audio, durationMs: 6807, words, contentType: "audio/wav", costCents: 0 }, targetDurationMs: timing.targetDurationMs }];
    const timeline = compileEditorialTimeline(job, timed.storyboard, timed.plan, assets, ["https://example.test/voice.wav"], "https://example.test/score.wav", undefined);
    expect(validateTimeline({ timeline, sourceBundle: draft.sourceBundle }).passed).toBe(true);
    const captions = timeline.tracks.find((track) => track.kind === "captions")!.segments;
    expect(captions.map((cue) => cue.metadata.text).join(" ")).toBe(narration);
    expect(timeline.durationMs - captions.at(-1)!.endMs).toBeGreaterThanOrEqual(3000);
    const width = aspectRatio === "16:9" ? 1280 : 720;
    const height = aspectRatio === "16:9" ? 720 : 1280;
    const source = { id: "evidence", sourceId: "source", fragmentId: "excerpt", kind: "url_excerpt_card" as const, title: "Methodology", locator: "Conclusion", excerpt: narration, excerptHash: "0".repeat(64) };
    const message = readableEditorialMessage("A reference with limits", narration, 3000);
    const base = await sharp(outlineEditorialText(sourceCardSvg(source, "A reference with limits", width, height, [], undefined, message))).png().toBuffer();
    await writeFile(join(directory!, `card-${aspectRatio.replace(":", "x")}.png`), base);
    const overlay = await sharp({ create: { width, height, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } }).png().toBuffer();
    const beats = timed.plan.beats.map((beat) => ({ beat, base, baseType: "image" as const, overlay }));
    const rendered = await renderEditorialAssets(job.id, job, beats, assets, await readFile(score), audio, timelineToAss(timeline, aspectRatio));
    const output = join(directory!, `natural-${aspectRatio.replace(":", "x")}.mp4`);
    await writeFile(output, rendered.video);
    await writeFile(join(directory!, `natural-${aspectRatio.replace(":", "x")}.json`), JSON.stringify(timeline, null, 2));
    const probe = await probeMediaFile(output);
    expect(probe.durationSeconds).toBeCloseTo(job.durationSeconds, 2);
    expect(probe.hasAudio).toBe(true);
    const duration = execFileSync("ffprobe", ["-v", "error", "-select_streams", "a:0", "-show_entries", "stream=duration", "-of", "default=nw=1:nk=1", output], { encoding: "utf8" });
    expect(Number(duration.trim())).toBeCloseTo(job.durationSeconds, 1);
    // The score remains audible after speech, including across its repeated seam.
    const samples = execFileSync("ffmpeg", ["-v", "error", "-ss", "7.3", "-i", output, "-t", "0.5", "-f", "f32le", "-ac", "1", "-ar", "8000", "pipe:1"]);
    let energy = 0; for (let i = 0; i < samples.length; i += 4) energy += samples.readFloatLE(i) ** 2;
    expect(Math.sqrt(energy / (samples.length / 4))).toBeGreaterThan(.0001);
  }, 120_000);
});
